### ISSUE TITLE
Auto*

### ISSUE THREAD

**Issue by roidelapluie** [jolshevski/puppet-spec#27]
Is it possible to test autorequires/autonotify with this host?

**Comment by jolshevski** [comment]
Currently, no. This is due to the fact that we aren't able to assert on the dependency graph, only the ordering metaparameters that are ultimately evaluated to construct the graph. This wasn't a concern to me initially because the resources responsible for the auto* behaviors should be tested in isolation, and should not be a consideration when testing any associated declarations. In other words, implicit dependencies are the responsibility of the definition, not the declaration.

That said, it wouldn't be difficult to add a resource type that is capable of asserting on the dependency graph itself. Something like `assert_edge`, `assert_before`, etc. This could be useful for role level integration tests now that I'm thinking about it.

Let me know if you think this would be of value. Feel free to take a stab at writing something up also.

**Comment by roidelapluie** [comment]
My use case is to test a puppet module with custom types/provider. I was thinking that puppet-spec
coult help to test the type itself (accepted parameters, generated dependencies, etc). Unfortunately I will not likely have any time to spend on this any time soon.

**Comment by roidelapluie** [comment]
Why are you closing this?

**Comment by jolshevski** [comment]
Apologies, I should have left a note when closing.

My intention in writing Puppet spec was to provide users who are unfamiliar with ruby/rspec with a simple means of testing their classes and defined types. I have no intention of supporting type/providers since anyone who is comfortable enough in Ruby to write one, will most likely also be able to write the associated rpsec tests using puppetlabs_spec_helper or similar.
